export enum PlacementPoints {
  FIRSTPLACE = 10,
  SECONDPLACE = 9,
  THIRDPLACE = 8,
  FOURTHPLACE = 7,
  FIFTHPLACE = 6,
  SIXTHPLACE = 5,
  SEVENTHPLACE = 4,
  EIGHTHPLACE = 3,
  NINETHPLACE = 2,
  TENTHPLACE = 1
}
